1번

CREATE TABLE ORDERS (
    ORDER_ID        NUMBER(12,0),
    ORDER_DATE      DATE ,
    ORDER_MODE      VARCHAR2(8 BYTE),
    CUSTOMER_ID     NUMBER(6,0),
    ORDER_STATUS    NUMBER(2,0) DEFAULT 0,
    ORDER_TOTAL     NUMBER(8,2),
    SALES_REP_ID	NUMBER(6,0),
    PROMOTION_ID	NUMBER(6,0),
    CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT CK_ORDER_MODE CHECK (ORDER_MODE IN ('direct','online'))
);

2번

CREATE TABLE ORDER_ITEMS (
    ORDER_ID        NUMBER(12,0),
    LINE_ITEM_ID    NUMBER(3,0),
    PRODUCT_ID      NUMBER(3,0),
    UNIT_PRICE      NUMBER(8,2),
    QUANTITY        NUMBER(8,0),
    CONSTRAINT ORDER_ITEMS_CS PRIMARY KEY (ORDER_ID, LINE_ITEM_ID)
);

3번

CREATE TABLE PROMOTIONS (
    PROMO_ID        NUMBER(6,0),
    PROMO_NAME      VARCHAR2(20),
    CONSTRAINT PROMOTIONS_CS PRIMARY KEY (PROMO_ID)
);

4번;



5번;

CREATE SEQUENCE ORDERS_SEQ
INCREMENT BY 1
START WITH 1000
MINVALUE 1
MAXVALUE 99999999
NOCYCLE
NOCACHE